name: FastApi CI Pipeline

on:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log Level'
        requried: true
        default: 'warning'
        type: choice
        options: 
        - info
        - warning
        - debug
      
      tags:
        description: 'Run tags'
        requried: false
        type: boolean


jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Set up python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies 
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync 
  